=== Maurigoo/WsLMSGI/ACTIVIDAD_15/actividad15.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ciudad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="20"/>
                            <xs:pattern value="[A-ZÃ‘][a-zA-Z]*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="poblacion">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="100"/>
                            <xs:maxInclusive value="100000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="alcalde">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                        <xs:pattern value="[A-Z][a-zA-Z]*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="apellidos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                        <xs:pattern value="[A-Z][a-zA-Z]*( [A-Z][a-zA-Z]*)?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="18"/>
                                        <xs:maxInclusive value="120"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\+34[0-9]{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tarjeta_credito" type="xs:string"/>
                            <xs:element name="correo_electronico">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="funcionarios" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="funcionario" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        
                                        <xs:element name="nombre_apellidos">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="50"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="codigo_postal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{5}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="fecha_nacimiento">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{2}/[0-9]{2}/[0-9]{4}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="contrasena" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z][\d]{2}[%!@$]{1}.{10}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="numero_cuenta_bancaria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="ES\d{4} \d{4} \d{4} \d{4}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Maurigoo/WsLMSGI/ACTIVIDAD_15/actividad15.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudad id="AB-12345" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation= "actividad15.xsd">
    <nombre>Madrid</nombre>
    <poblacion>50000</poblacion>
    <alcalde>
        <nombre>Javier</nombre>
        <apellidos>Gomez Perez</apellidos>
        <edad>45</edad>
        <telefono>+34661435678</telefono>
        <tarjeta_credito>1234567890123456</tarjeta_credito>
        <correo_electronico>javier@gmail.com</correo_electronico>
    </alcalde>
    <funcionarios>
        <funcionario id="1">
            <nombre_apellidos>Juan Martínez López</nombre_apellidos>
            <codigo_postal>28001</codigo_postal>
            <fecha_nacimiento>01/01/1990</fecha_nacimiento>
            <!-- No valida la contraseña con nada, no se cual es el error :( -->
            <contrasena>V57!ql8Hm2hPnG</contrasena>
            <numero_cuenta_bancaria>ES1234 5678 9012 3456</numero_cuenta_bancaria>
        </funcionario>
        <funcionario id="2">
            <nombre_apellidos>Maria González</nombre_apellidos>
            <codigo_postal>08001</codigo_postal>
            <fecha_nacimiento>15/06/1985</fecha_nacimiento>
            <contrasena>V57!ql8Hm2hPnG</contrasena>
            <numero_cuenta_bancaria>ES9876 5432 1098 7654</numero_cuenta_bancaria>
        </funcionario>
    </funcionarios>
</ciudad>
