=== Maurigoo/WsLMSGI/ACTIVIDAD_12/videojuego.dtd
<!ELEMENT videojuego (nombre, fecha_creacion, nota, programadores, compania, pagina_web)>
    <!ATTLIST videojuego id CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT fecha_creacion (#PCDATA)>
    <!ELEMENT nota (#PCDATA)>
    
    <!ELEMENT programadores (programador+)>
    <!ELEMENT programador (nombre_programador, apellidos, dni, fecha_nacimiento, direccion)>
    <!ATTLIST programador number CDATA #REQUIRED>
    <!ELEMENT nombre_programador (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT fecha_nacimiento (#PCDATA)>
    
    <!ELEMENT direccion (tipo_via, nombre_via, codigo_postal, pais)>
    <!ELEMENT tipo_via (#PCDATA)>
    <!ELEMENT nombre_via (#PCDATA)>
    <!ELEMENT codigo_postal (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    
    <!ELEMENT compania (nombre_compania, nif, direccion_compania)>
    <!ATTLIST compania identificador_unico CDATA #REQUIRED>
    <!ELEMENT nombre_compania (#PCDATA)>
    <!ELEMENT nif (#PCDATA)>
    <!ELEMENT direccion_compania (tipo_via, nombre_via, codigo_postal, pais)>
    
    <!ELEMENT pagina_web (#PCDATA)>

=== Maurigoo/WsLMSGI/ACTIVIDAD_12/VideojuegoExt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videojuego SYSTEM "videojuego.dtd">
<videojuego id="2">
    <nombre>Apex Legends</nombre>
    <fecha_creacion>04/02/2019</fecha_creacion>
    <nota>9</nota>

    <programadores>
        <programador number="One :)">
            <nombre_programador>Luis</nombre_programador>
            <apellidos>Gonzalez</apellidos>
            <dni>12345678A</dni>
            <fecha_nacimiento>15/08/1992</fecha_nacimiento>
            <direccion>
                <tipo_via>Avenida</tipo_via>
                <nombre_via>Paseo de la Castellana</nombre_via>
                <codigo_postal>28046</codigo_postal>
                <pais>España</pais>
            </direccion>
        </programador>

        <programador number="Two :)">
            <nombre_programador>Ana</nombre_programador>
            <apellidos>Ruiz</apellidos>
            <dni>98765432B</dni>
            <fecha_nacimiento>22/05/1988</fecha_nacimiento>
            <direccion>
                <tipo_via>Calle</tipo_via>
                <nombre_via>Velazquez</nombre_via>
                <codigo_postal>28001</codigo_postal>
                <pais>España</pais>
            </direccion>
        </programador>
    </programadores>

    <compania identificador_unico="Alpha">
        <nombre_compania>NovaGaming</nombre_compania>
        <nif>ABC123456</nif>
        <direccion_compania>
            <tipo_via>Calle</tipo_via>
            <nombre_via>Gran Via</nombre_via>
            <codigo_postal>28013</codigo_postal>
            <pais>España</pais>
        </direccion_compania>
    </compania>

    <pagina_web>
    <![CDATA[
    <html>
     <body>
        <h1 style="text-align: center;">Bienvenido al Apex Legends</h1>
        <h2 style="color: blue;text-align: center;" >¡Prepárate para la acción!</h2>
        <img src=https://th.bing.com/th/id/OIP.PsGWd3xq_p2dD0H4BiK0RgHaEK?rs=1&pid=ImgDetMain/>
     </body>
    </html>    
    ]]>
    </pagina_web>
</videojuego>
