=== Maurigoo/WsLMSGI/ACTIVIDAD_14/actividad14.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="15"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="española" type="xs:boolean"/>
                <xs:element name="capital_social">
                    <xs:simpleType>
                        <xs:restriction base="xs:double">
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="direccion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipo_via">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Calle"></xs:enumeration>
                                        <xs:enumeration value="Plaza"></xs:enumeration>
                                        <xs:enumeration value="Via"></xs:enumeration>
                                        <xs:enumeration value="Camino"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombre_via" type="xs:string"/>
                            <xs:element name="CP" type="xs:string"/>
                            <xs:element name="pais" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellidos" type="xs:string" minOccurs="1"/>
                                        <xs:element name="extranjero" type="xs:boolean"/>
                                        <xs:element name="fecha_nacimiento" type="xs:date"/>
                                        <xs:element name="salario">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="900"></xs:minInclusive>
                                                    <xs:maxExclusive value="5000"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="direccion" minOccurs="1" maxOccurs="2">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="direccion">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:maxLength value="250"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="pais" type="xs:string"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="esta_casado" type="xs:boolean" minOccurs="0"/>
                                        <xs:element name="capital_social">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:double">
                                                        <xs:attribute name="moneda">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="euros"/>
                                                                    <xs:enumeration value="dolares"/>
                                                                    <xs:enumeration value="yenes"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="DNI" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:length value="9"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fecha_creacion" type="xs:date" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="NIF" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="9"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="pais" type="xs:string" default="España"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Maurigoo/WsLMSGI/ACTIVIDAD_14/actividad14.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa NIF="123456789" pais="España" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "actividad14.xsd">
    <nombre>Upgrade</nombre>
    <española>true</española>
    <capital_social>101500.50</capital_social>
    <direccion>
        <tipo_via>Calle</tipo_via>
        <nombre_via>Orense</nombre_via>
        <CP>28022</CP>
        <pais>España</pais>
    </direccion>
    <empleados>
        <empleado DNI="12458514J">
            <nombre>Juan</nombre>
            <apellidos>Pérez</apellidos>
            <extranjero>false</extranjero>
            <fecha_nacimiento>1990-05-15</fecha_nacimiento>
            <salario>3000</salario>
            <direccion>
                <direccion>C\Orense 62, Madrid</direccion>
                <pais>España</pais>
            </direccion>
            <esta_casado>true</esta_casado>
            <capital_social moneda="euros">50000</capital_social>
        </empleado>
        <empleado DNI="95748563P">
            <nombre>Maria</nombre>
            <apellidos>Gomez</apellidos>
            <extranjero>true</extranjero>
            <fecha_nacimiento>1985-10-20</fecha_nacimiento>
            <salario>2500</salario>
            <direccion>
                <direccion>Rue Principale</direccion>
                <pais>Francia</pais>
            </direccion>
            <esta_casado>false</esta_casado>
            <capital_social moneda="dolares">3000</capital_social>
        </empleado>
    </empleados>
    <fecha_creacion>2000-01-01</fecha_creacion>
</empresa>
